import = ["~/workspace/github.com/woobay/dotfiles/alacritty/catppuccin.toml"]

[shell]
program = "/bin/bash"
args = ["-l"]

[font]
size = 14

[font.normal]
family = "Hack Nerd Font Mono"

[window]
decorations = "none"

[window.padding]
x = 7
y = 7
