import = ["~/.config/alacritty/themes/themes/deep_space.toml"]

[shell]
program = "/bin/bash"
args = ["-l"]

[font]
size = 14

#[font.normal]
#family = "UbuntuMono Nerd Front"

[window]
decorations = "none"

[window.padding]
x = 7
y = 7
